name = "Spec2Struc"
uuid = "44c939e5-f9c7-478c-a795-a0678313fc8a"
authors = ["Haina Wang"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
